import Link from 'next/link';
import type { ReactNode } from 'react';
import { type RequestView, formatDate, formatDateTime, shortRequestId, statusColor, statusLabels, urgencyColor, urgencyLabels } from './demo-data';
import { Badge, basePath, Heading, Icon, SectionTitle } from './ui';
import CloseRequestButton from './CloseRequestButton';

function Details({ rows }: { rows: [string, ReactNode][] }) { return <dl className="detail-list">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>; }
export default function RequestDetail({ request: r }: { request: RequestView }) {
  const editable = r.status === 'OPEN' || r.status === 'IN_PROGRESS';
  return <><Heading title="รายละเอียดคำร้องขอเลือด" subtitle="ตรวจสอบข้อมูล ติดตามสถานะ และการตอบรับ"><div className="heading-actions"><Link className="button" href={basePath}><Icon name="arrow" />กลับ</Link>{editable ? <Link className="button" href={`${basePath}/${r.id}/edit`}>แก้ไขคำร้อง</Link> : <button className="button" disabled>แก้ไขคำร้อง</button>}{editable ? <CloseRequestButton requestId={r.id} /> : <button className="button primary" disabled>ปิดคำร้องแล้ว</button>}</div></Heading>
    <section className="card request-summary"><div className="request-identity"><span className="blood-large">{r.blood}</span><div><h2 title={r.id}>คำร้องขอเลือด #{shortRequestId(r.id)}</h2><h3><Icon name="hospital" />{r.hospital}</h3><p>จ.{r.province}</p><small>สร้างเมื่อ {formatDateTime(r.createdAt)}</small></div></div><div className="summary-right"><div className="summary-badges"><Badge color={urgencyColor(r.urgency)}>{r.urgency} - {urgencyLabels[r.urgency]}</Badge><Badge color={statusColor(r.status)}>{statusLabels[r.status]}</Badge></div><div className="mini-stats"><div><Icon name="clock" /><span><small>วันที่ต้องการเลือด</small><b>{formatDate(r.date)}</b></span></div><div><Icon name="drop" /><span><small>จำนวนที่ต้องการ</small><b>{r.units} ยูนิต</b></span></div><div><Icon name="users" /><span><small>รายการบริจาคที่เกี่ยวข้อง</small><b>{r.responseCount} รายการ</b></span></div></div></div></section>
    <nav className="card tabs" aria-label="ส่วนรายละเอียด"><a href="#information"><Icon name="file" />รายละเอียด</a><a href="#donors"><Icon name="users" />ผู้บริจาคที่ตอบรับ</a><a href="#timeline"><Icon name="clock" />ประวัติสถานะ</a></nav>
    <div className="detail-layout"><div><section className="card" id="information"><SectionTitle>ข้อมูลคำร้อง</SectionTitle><Details rows={[
      ['โรงพยาบาล / หน่วยงาน', r.hospital], ['จังหวัด', r.province], ['ที่อยู่', r.address], ['กรุ๊ปเลือดที่ต้องการ', <Badge key="blood" color="red">{r.blood}</Badge>], ['จำนวนโลหิตที่ต้องการ', `${r.units} ยูนิต`], ['ระดับความเร่งด่วน', urgencyLabels[r.urgency]], ['วันที่ต้องการเลือด', formatDate(r.date)], ['รายละเอียดเคส / การรักษา', r.purpose],
    ]} /></section></div><div><section className="card"><SectionTitle icon="hospital">สถานที่และข้อมูลติดต่อ</SectionTitle><Details rows={ [['ที่อยู่', r.address], ['ชื่อผู้ติดต่อ', r.contact], ['เบอร์ติดต่อ', r.phone]] } /></section><section className="card" id="timeline"><SectionTitle icon="clock">สถานะคำร้อง</SectionTitle><ol className="timeline"><li className="current"><div>{statusLabels[r.status]}<small>สร้างเมื่อ {formatDateTime(r.createdAt)}</small></div></li></ol><p className="form-hint">ฐานข้อมูลยังไม่มีตารางประวัติการเปลี่ยนสถานะ จึงแสดงเฉพาะสถานะปัจจุบัน</p></section><section className="card donors" id="donors"><SectionTitle icon="users">รายการบริจาคที่เกี่ยวข้อง</SectionTitle><strong>{r.responseCount} รายการ</strong><p>{r.responseCount ? 'พบรายการบริจาคที่เชื่อมกับคำร้องนี้' : 'ยังไม่มีรายการบริจาคที่เชื่อมกับคำร้องนี้'}</p></section></div></div>
  </>;
}
